var express = require('express');
var router = express.Router();
var fs = require('fs');


// In the real program this will be generated by a database call
var data = {
    "courses" : {
        "ACT" : {
            "English" : true,
            "Math" : true,
            "Reading" : true,
            "Science" : true,
            "Essay" : true,
            "Practice" : true
        }
    },
    "videos" : {
        "ACTmath1" : {
            "completion": true,
            "time" : "0",
            "uri": "https://www.youtube.com/embed/9szNGXja85M"
        },
        "ACTmath2" : {
            "completion" : true,
            "time" : "0",
            "uri": "https://www.youtube.com/embed/9szNGXja85M"
        },
        "ACTmath3" : {
            "completion" : false,
            "time" : "35",
            "uri": "https://www.youtube.com/embed/9szNGXja85M"
        }
    },
    "profile" : {
        "firstName" : "Rick",
        "lastName" : "Sanchez",
        "image" : "https://i.ytimg.com/vi/AzZ4K1OzomE/maxresdefault.jpg"
    },
    "orders" : {
        "Complete ACT Prep Package" : "z07d6j6i76"
    },
    "settings": {
        "recommendContent" : "checked",
        "resetPassword" : "dummylink.js",
        "offlineContent" : "checked"
    }
};

var videos = {};

// In the real program a script will refresh this file every so often

fs.readFile('writeto.txt', 'utf8', function(err, contents) {
    if (videos) {
    videos = JSON.parse(contents);
        }
    else {
        router.use();
    }
});

module.exports = router;

router.get('/', function(req, res) {
    res.render('dashboard', {
        data : data
    });
});

// router.get('/', function(req, res) {
//     res.render('dashboard', {
//         name : user["profileData"]["firstName"],
//         courseName : Object.keys(user["courses"])[0]
//     });
// });
