var express = require('express');
var router = express.Router();
var fs = require('fs');


// In the real program this will be generated by a database call
var user = {
    "courses" : {
        "ACT" : {
            "English" : true,
            "Math" : true,
            "Reading" : true,
            "Science" : true,
            "Essay" : true,
            "Practice" : true
        }
    },
    "videos" : {
        "ACTmath1" : {
            "completion": true,
            "uri": "https://image.flaticon.com/icons/svg/34/34099.svg"
        },
        "ACTmath2" : {
            "completion" : true,
            "uri": "https://image.flaticon.com/icons/svg/34/34099.svg"
        },
        "ACTmath3" : {
            "completion" : "0m35s",
            "uri": "https://image.flaticon.com/icons/svg/34/34099.svg"
        }
    },
    "profileData" : {
        "firstName" : "Rick",
        "lastName" : "Sanchez",
        "image" : "https://i.ytimg.com/vi/AzZ4K1OzomE/maxresdefault.jpg"
    },
    "orderData" : {
        "ACT" : "z07d6j6i76"
    },
    "settingsData": {
        "recommendContent" : true,
        "resetPassword" : "dummylink.js",
        "offlineContent" : false
    }
};

var videos = {};

// In the real program a script will refresh this file every so often

fs.readFile('writeto.txt', 'utf8', function(err, contents) {
    if (videos) {
    videos = JSON.parse(contents);
        }
    else {
        router.use();
    }
});

module.exports = router;

router.get('/', function(req, res) {
    res.render('dashboard', {
        name : user["profileData"]["firstName"],
        courses : user["courses"],
        orders : user["orderData"],
        settings : user["settingsData"]
    });
});